spring.application.name=task-manager
spring.thymeleaf.prefix=classpath:/config/templates/

spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.url=${DATABASE_URL}
spring.jpa.hibernate.ddl-auto=update
app.base-url=http://localhost:8080
logging.level.org.springframework.security=DEBUG


app.jwt.expiration-ms=604800000
app.jwt.refresh-ms=15552000000
app.jwt.secret=${JWT_SECRET}

# Your Google Cloud Project ID
gcp.project.id=couple-task-manager-458414
# The region where you are using Vertex AI (e.g., us-central1)
gcp.region=us-central1
# The specific Imagen model you want to use
gcp.model.name=imagen-3.0-generate-002

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent
gemini.imagen.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp-image-generation:generateContent

app.cors.allowed-origins=http://localhost:4200, http://localhost:8100, capacitor://localhost, http://localhost