spring.application.name=task-manager
spring.thymeleaf.prefix=classpath:/config/templates/

spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.url=${DATABASE_URL}
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
logging.level.org.springframework.security=DEBUG